---
# Some magic for the Vagrant demo.
# Copy any external requests into the RootCA
- name: import requests
  import_tasks: vagrant-to-root.yml
  tags: [ setup ]

# ROOT CA SETUP
- name: setup root CA
  import_tasks: rootca.yml
  tags: [ setup ]

# Some magic for the Vagrant demo.
# export any created certificates to the host
- name: export certificates
  import_tasks: root-to-vagrant.yml
  tags: [ setup ]
